// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prueba2.Data;

namespace prueba2.Migrations
{
    [DbContext(typeof(prueba2Context))]
    [Migration("20201002054017_addinicial")]
    partial class addinicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prueba2.Models.contratos", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fechafin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechainicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreentidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numerocontrato")
                        .HasColumnType("int");

                    b.Property<long?>("trabajadoresId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("trabajadoresId");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("prueba2.Models.trabajadores", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("fechadenacimineto")
                        .HasColumnType("datetime2");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("primerapellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primernombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoapellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundonombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoindetificacion")
                        .HasColumnType("int");

                    b.Property<long?>("trabajadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("trabajadores");
                });

            modelBuilder.Entity("prueba2.Models.contratos", b =>
                {
                    b.HasOne("prueba2.Models.trabajadores", null)
                        .WithMany("contrato")
                        .HasForeignKey("trabajadoresId");
                });

            modelBuilder.Entity("prueba2.Models.trabajadores", b =>
                {
                    b.HasOne("prueba2.Models.contratos", "contratos")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
